# Generated by Django 4.2.7 on 2024-02-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=500, unique=True)),
                ('modification_log', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=500)),
                ('published_date', models.DateField(max_length=1000)),
                ('distribution_expense', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modification_log', models.CharField(max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense_tracking_app.book_type')),
            ],
        ),
    ]
