# Generated by Django 4.2.7 on 2024-02-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0002_alter_books_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='idNumber',
            field=models.IntegerField(),
        ),
    ]
