# Generated by Django 4.2.7 on 2024-02-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0003_alter_books_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
