# Generated by Django 4.2.7 on 2024-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0010_profile_user_group_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_group',
        ),
    ]
