# Generated by Django 4.2.7 on 2024-03-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0012_profile_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_type',
            name='type_name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
