# Generated by Django 4.2.7 on 2024-03-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0013_alter_book_type_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='expense_tracking_app.book_type'),
        ),
    ]
