# Generated by Django 4.2.7 on 2024-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0015_alter_books_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.svg', upload_to='User_images'),
        ),
    ]
