# Generated by Django 4.2.7 on 2024-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracking_app', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='idNumber',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
